### ISSUE TITLE
Combat-seq in two batches of RNA-seq with different reference genomes.

### ISSUE THREAD

**Issue by lincj1994** [jtleek/sva-devel#49]
Hi. We have performed two batches of RNA sequencing with **different piplines** and thus, generated two different count matrices. Besides, **one is hg38 and the other is hg19**. 
**My first question** is if I can performed batch correction using ComBat function (or combat-seq) since different upstream pipeline and different reference genome was used. 
**The second question** is if there is any other methods to correct the batch effect for such a condition. Btw, there were some samples that were sequenced in both two batches of RNA seq. I dont know if this clue can provide any hints

**Comment by wevanjohnson** [comment]
ComBat-Seq should work okay on these data, technically this would be a cross-platform adjustment, and ComBat usually works well in this scenario. 

However, by far, the best thing to do would be to reprocess the datasets with the same processing and alignment method. There is a cost to batch adjustment—it cannot fix everything and it does lead to random errors due to under/over correction, and in your case the processing pipeline effect is completely preventable if you have access to the raw data.
